# Generated by Django 5.1.1 on 2024-09-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_courses_tbl_alumni_placement_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(null=True)),
                ('event_link', models.TextField(max_length=50, null=True)),
                ('posted_date', models.DateField(null=True)),
            ],
        ),
    ]
