# Generated by Django 5.1.1 on 2024-09-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tbl_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_event',
            name='event_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
