# Generated by Django 5.1.1 on 2024-09-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_tbl_event_event_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_event',
            old_name='event',
            new_name='events',
        ),
    ]
