# Generated by Django 5.1.1 on 2024-09-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_event_tbl_event_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_courses',
            name='view_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
